name: dockerarc-action

run-name: DockerArc is in action

env:
    API_KEY: ${{ secrets.DOCKERTEST_API_KEY }}

on:
    push:
        paths:
            # - Python/DockerArc/**
            - .github/workflows/dockerarc-action.yml

jobs:
    run-app:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: docker build -t arcgis-image Python/DockerArc
            - run: docker run arcgis-image
