name: pypush_demo

run-name: ${{ github.repository }} is working with actions.

env: 
    SECRET: 'do it work??'

on: [push]
    # push:
    #     paths:
    #         - 'Python/GithubActionsDemo/**'

jobs:
    hello-world:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: pip install python-dotenv
            - run: python Python/GithubActionsDemo/demo.py